// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: wormhole/v1/query.proto

package wormholev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Config_FullMethodName           = "/wormhole.v1.Query/Config"
	Query_WormchainChannel_FullMethodName = "/wormhole.v1.Query/WormchainChannel"
	Query_GuardianSets_FullMethodName     = "/wormhole.v1.Query/GuardianSets"
	Query_GuardianSet_FullMethodName      = "/wormhole.v1.Query/GuardianSet"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Config returns the current module configuration.
	Config(ctx context.Context, in *QueryConfig, opts ...grpc.CallOption) (*QueryConfigResponse, error)
	// WormchainChannel returns the current channel opened to Wormchain.
	WormchainChannel(ctx context.Context, in *QueryWormchainChannel, opts ...grpc.CallOption) (*QueryWormchainChannelResponse, error)
	// GuardianSets returns all guardian sets registered in the module.
	GuardianSets(ctx context.Context, in *QueryGuardianSets, opts ...grpc.CallOption) (*QueryGuardianSetsResponse, error)
	// GuardianSet returns a specific guardian set given an index.
	GuardianSet(ctx context.Context, in *QueryGuardianSet, opts ...grpc.CallOption) (*QueryGuardianSetResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Config(ctx context.Context, in *QueryConfig, opts ...grpc.CallOption) (*QueryConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryConfigResponse)
	err := c.cc.Invoke(ctx, Query_Config_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) WormchainChannel(ctx context.Context, in *QueryWormchainChannel, opts ...grpc.CallOption) (*QueryWormchainChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryWormchainChannelResponse)
	err := c.cc.Invoke(ctx, Query_WormchainChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GuardianSets(ctx context.Context, in *QueryGuardianSets, opts ...grpc.CallOption) (*QueryGuardianSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGuardianSetsResponse)
	err := c.cc.Invoke(ctx, Query_GuardianSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GuardianSet(ctx context.Context, in *QueryGuardianSet, opts ...grpc.CallOption) (*QueryGuardianSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryGuardianSetResponse)
	err := c.cc.Invoke(ctx, Query_GuardianSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	// Config returns the current module configuration.
	Config(context.Context, *QueryConfig) (*QueryConfigResponse, error)
	// WormchainChannel returns the current channel opened to Wormchain.
	WormchainChannel(context.Context, *QueryWormchainChannel) (*QueryWormchainChannelResponse, error)
	// GuardianSets returns all guardian sets registered in the module.
	GuardianSets(context.Context, *QueryGuardianSets) (*QueryGuardianSetsResponse, error)
	// GuardianSet returns a specific guardian set given an index.
	GuardianSet(context.Context, *QueryGuardianSet) (*QueryGuardianSetResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Config(context.Context, *QueryConfig) (*QueryConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Config not implemented")
}
func (UnimplementedQueryServer) WormchainChannel(context.Context, *QueryWormchainChannel) (*QueryWormchainChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WormchainChannel not implemented")
}
func (UnimplementedQueryServer) GuardianSets(context.Context, *QueryGuardianSets) (*QueryGuardianSetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuardianSets not implemented")
}
func (UnimplementedQueryServer) GuardianSet(context.Context, *QueryGuardianSet) (*QueryGuardianSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuardianSet not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Config_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Config(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Config_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Config(ctx, req.(*QueryConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_WormchainChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWormchainChannel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).WormchainChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_WormchainChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).WormchainChannel(ctx, req.(*QueryWormchainChannel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GuardianSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGuardianSets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GuardianSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GuardianSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GuardianSets(ctx, req.(*QueryGuardianSets))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GuardianSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGuardianSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GuardianSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GuardianSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GuardianSet(ctx, req.(*QueryGuardianSet))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wormhole.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Config",
			Handler:    _Query_Config_Handler,
		},
		{
			MethodName: "WormchainChannel",
			Handler:    _Query_WormchainChannel_Handler,
		},
		{
			MethodName: "GuardianSets",
			Handler:    _Query_GuardianSets_Handler,
		},
		{
			MethodName: "GuardianSet",
			Handler:    _Query_GuardianSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wormhole/v1/query.proto",
}
